osx_image: xcode7

language: objective-c

before_install:
- brew update
- brew outdated xctool || brew upgrade xctool

script:
- xctool clean build -workspace JSQCoreDataKit.xcworkspace -scheme ExampleModel -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

- xctool clean build test -workspace JSQCoreDataKit.xcworkspace -scheme JSQCoreDataKit -sdk iphonesimulator9.0 ONLY_ACTIVE_ARCH=NO
- xctool clean build test -workspace JSQCoreDataKit.xcworkspace -scheme JSQCoreDataKit -sdk iphonesimulator8.1 ONLY_ACTIVE_ARCH=NO
